server:
  port: 9090
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: backend
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: user
    password: password
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    csrf:
      enabled: true
  override-with-generic-response: false
